apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    env: dev    
spec:
  replicas: 6
  selector: 
    matchLabels:
      tier: web-server2
  template:
    metadata:
      name: calebespinoza
      labels:
        tier: web-server2
    spec:
      containers:
      - name: calebespinoza
        image: calebespinoza/store-products:2.0 
        ports:
        - containerPort: 80