apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-server-rs
  labels:
    env: dev    
spec:
  replicas: 5
  selector: 
    matchLabels:
      tier: web-server1
  template:
    metadata:
      name: jenkins
      labels:
        tier: web-server1
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080