apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: MSQL_SA_PASSWORD
        valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SQ_PASSWORD