apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 8001
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 8001
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: prod
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 8001
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"